// ==================== ЯЗЫКОВОЙ ПАКЕТ ====================
const LANGUAGES = {
    ru: {
        menu_title: 'MONOPOLY',
        menu_local: '🎮 Играть локально',
        menu_bot: '🤖 Играть с ботами',
        menu_online_create: '🌐 Создать онлайн-комнату',
        menu_online_join: '🔗 Присоединиться к комнате',
        menu_load: '💾 Загрузить игру',
        menu_settings: '⚙️ Настройки',
        menu_rules: '📜 Правила',
        menu_footer: 'Курсовой проект · Вилданов Р.Р. · ЧЭнК · ИСП-7-23',
        loading: 'ЗАГРУЗКА МОНОПОЛИИ',
        settings_title: '⚙️ НАСТРОЙКИ',
        settings_start_money: 'Стартовый капитал:',
        settings_money_1000: '1000$ (Быстрая)',
        settings_money_1500: '1500$ (Классика)',
        settings_money_2000: '2000$ (Богатая)',
        settings_money_2500: '2500$ (Олигарх)',
        settings_bot_count: 'Количество ботов:',
        settings_bot_1: '1 бот',
        settings_bot_2: '2 бота',
        settings_bot_3: '3 бота',
        settings_anim_speed: 'Скорость анимации:',
        settings_anim_fast: 'Быстрая',
        settings_anim_normal: 'Нормальная',
        settings_anim_slow: 'Медленная',
        settings_sound: 'Звуки:',
        settings_sound_on: 'Включены',
        settings_sound_off: 'Выключены',
        settings_mode: 'Режим:',
        settings_mode_normal: 'Обычный',
        settings_mode_fast: 'Быстрая игра',
        settings_language: 'Язык:',
        settings_lang_ru: '🇷🇺 Русский',
        settings_lang_en: '🇬🇧 English',
        settings_save: '💾 СОХРАНИТЬ',
        token_title: '🎨 ВЫБЕРИТЕ ФИГУРКИ',
        token_players: 'Количество игроков:',
        token_players_2: '2 игрока',
        token_players_3: '3 игрока',
        token_players_4: '4 игрока',
        token_start: '🎯 НАЧАТЬ ИГРУ',
        token_back: '↩️ НАЗАД',
        load_title: '💾 ЗАГРУЗИТЬ ИГРУ',
        load_empty: 'Пусто',
        load_back: '↩️ НАЗАД',
        load_slot: 'Слот',
        rules_title: '📖 ПРАВИЛА ИГРЫ',
        rules_text: `<p><strong>1. Цель:</strong> Остаться единственным необанкротившимся игроком.</p><p><strong>2. Старт:</strong> Каждый получает стартовый капитал. Проход СТАРТА +200$.</p><p><strong>3. Покупка:</strong> Свободные улицы можно купить. Отказ → аукцион.</p><p><strong>4. Дома:</strong> Соберите все улицы одного цвета → можно строить дома (до 4) и отель.</p><p><strong>5. Залог:</strong> Нужны деньги? Заложите недвижимость за 50% стоимости.</p><p><strong>6. Торговля:</strong> Обменивайтесь улицами и деньгами с другими игроками.</p><p><strong>7. Тюрьма:</strong> ПОЛИЦИЯ или карта → 3 хода или дубль.</p><p><strong>8. Шанс/Казна:</strong> Случайные события.</p><p><strong>9. Поля:</strong> Кнопка "ПОЛЯ" покажет историю каждой улицы!</p>`,
        game_roll: '🎲 БРОСИТЬ',
        game_end_turn: '⏩ ЗАВЕРШИТЬ',
        game_build: '🏗️ СТРОИТЬ',
        game_fields: '📋 ПОЛЯ',
        game_menu: '🏠 МЕНЮ',
        game_save: '💾',
        game_trade: '🤝',
        game_mortgage: '🏦',
        game_history: '📋 ИСТОРИЯ ХОДОВ',
        game_stats: '📊 СТАТИСТИКА',
        game_time: '00:00',
        game_turn: 'Ход',
        game_message: 'Нажмите "БРОСИТЬ"',
        game_your_turn: '🎯 Ваш ход!',
        game_turn_of: '⏳ Ход игрока:',
        game_jail_turn: '🔒 Ваш ход (в тюрьме)!',
        buy_price: '💰 Цена:',
        buy_rent: '📈 Аренда:',
        buy_buy: '💰 КУПИТЬ',
        buy_auction: '🔨 АУКЦИОН',
        auction_title: '🔨 АУКЦИОН:',
        auction_start: 'Стартовая цена:',
        auction_current: 'Текущая ставка:',
        auction_bidder: 'Участник:',
        auction_bid: '📈 СДЕЛАТЬ СТАВКУ',
        auction_pass: '🚫 ПАС',
        build_title: '🏗️ СТРОИТЕЛЬСТВО',
        build_close: 'ЗАКРЫТЬ',
        mortgage_title: '🏦 ЗАЛОГ НЕДВИЖИМОСТИ',
        mortgage_close: 'ЗАКРЫТЬ',
        trade_title: '🤝 ТОРГОВЛЯ',
        trade_you_offer: 'Вы предлагаете',
        trade_partner_offer: 'Партнёр предлагает',
        trade_money: 'Деньги',
        trade_propose: '📨 ПРЕДЛОЖИТЬ',
        trade_close: 'ЗАКРЫТЬ',
        trade_response_accept: '✅ ПРИНЯТЬ',
        trade_response_reject: '❌ ОТКЛОНИТЬ',
        chat_title: '💬 ЧАТ',
        chat_placeholder: 'Сообщение...',
        confirm_yes: 'ДА',
        confirm_no: 'НЕТ',
        confirm_exit: 'Выйти в меню? Прогресс будет потерян!',
    },
    en: {
        menu_title: 'MONOPOLY',
        menu_local: '🎮 Play Local',
        menu_bot: '🤖 Play with Bots',
        menu_online_create: '🌐 Create Online Room',
        menu_online_join: '🔗 Join Room',
        menu_load: '💾 Load Game',
        menu_settings: '⚙️ Settings',
        menu_rules: '📜 Rules',
        menu_footer: 'Course Project · Vildanov R.R. · ChEnK · ISP-7-23',
        loading: 'LOADING MONOPOLY',
        settings_title: '⚙️ SETTINGS',
        settings_start_money: 'Starting capital:',
        settings_money_1000: '$1000 (Quick)',
        settings_money_1500: '$1500 (Classic)',
        settings_money_2000: '$2000 (Rich)',
        settings_money_2500: '$2500 (Oligarch)',
        settings_bot_count: 'Number of bots:',
        settings_bot_1: '1 bot',
        settings_bot_2: '2 bots',
        settings_bot_3: '3 bots',
        settings_anim_speed: 'Animation speed:',
        settings_anim_fast: 'Fast',
        settings_anim_normal: 'Normal',
        settings_anim_slow: 'Slow',
        settings_sound: 'Sound:',
        settings_sound_on: 'On',
        settings_sound_off: 'Off',
        settings_mode: 'Mode:',
        settings_mode_normal: 'Normal',
        settings_mode_fast: 'Quick Game',
        settings_language: 'Language:',
        settings_lang_ru: '🇷🇺 Русский',
        settings_lang_en: '🇬🇧 English',
        settings_save: '💾 SAVE',
        token_title: '🎨 SELECT TOKENS',
        token_players: 'Number of players:',
        token_players_2: '2 players',
        token_players_3: '3 players',
        token_players_4: '4 players',
        token_start: '🎯 START GAME',
        token_back: '↩️ BACK',
        load_title: '💾 LOAD GAME',
        load_empty: 'Empty',
        load_back: '↩️ BACK',
        load_slot: 'Slot',
        rules_title: '📖 GAME RULES',
        rules_text: `<p><strong>1. Goal:</strong> Be the last player remaining without going bankrupt.</p><p><strong>2. Start:</strong> Each player receives starting capital. Passing GO gives +$200.</p><p><strong>3. Purchase:</strong> Free properties can be bought. Decline → auction.</p><p><strong>4. Houses:</strong> Collect all properties of one color → build houses (up to 4) and hotel.</p><p><strong>5. Mortgage:</strong> Need money? Mortgage property for 50% of value.</p><p><strong>6. Trade:</strong> Exchange properties and money with other players.</p><p><strong>7. Jail:</strong> POLICE or card → 3 turns or double.</p><p><strong>8. Chance/Chest:</strong> Random events.</p><p><strong>9. Fields:</strong> "FIELDS" button shows history of each street!</p>`,
        game_roll: '🎲 ROLL',
        game_end_turn: '⏩ END TURN',
        game_build: '🏗️ BUILD',
        game_fields: '📋 FIELDS',
        game_menu: '🏠 MENU',
        game_save: '💾',
        game_trade: '🤝',
        game_mortgage: '🏦',
        game_history: '📋 GAME LOG',
        game_stats: '📊 STATISTICS',
        game_time: '00:00',
        game_turn: 'Turn',
        game_message: 'Press "ROLL"',
        game_your_turn: '🎯 Your turn!',
        game_turn_of: '⏳ Turn:',
        game_jail_turn: '🔒 Your turn (in jail)!',
        buy_price: '💰 Price:',
        buy_rent: '📈 Rent:',
        buy_buy: '💰 BUY',
        buy_auction: '🔨 AUCTION',
        auction_title: '🔨 AUCTION:',
        auction_start: 'Starting price:',
        auction_current: 'Current bid:',
        auction_bidder: 'Bidder:',
        auction_bid: '📈 PLACE BID',
        auction_pass: '🚫 PASS',
        build_title: '🏗️ CONSTRUCTION',
        build_close: 'CLOSE',
        mortgage_title: '🏦 MORTGAGE PROPERTIES',
        mortgage_close: 'CLOSE',
        trade_title: '🤝 TRADE',
        trade_you_offer: 'You offer',
        trade_partner_offer: 'Partner offers',
        trade_money: 'Money',
        trade_propose: '📨 PROPOSE',
        trade_close: 'CLOSE',
        trade_response_accept: '✅ ACCEPT',
        trade_response_reject: '❌ REJECT',
        chat_title: '💬 CHAT',
        chat_placeholder: 'Message...',
        confirm_yes: 'YES',
        confirm_no: 'NO',
        confirm_exit: 'Return to menu? Progress will be lost!',
    }
};

let currentLang = 'ru';

function t(key) {
    const lang = LANGUAGES[currentLang] || LANGUAGES['ru'];
    return lang[key] || LANGUAGES['ru'][key] || key;
}

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('monopoly_language', lang);
    updateAllTexts();
}

function loadLanguage() {
    const saved = localStorage.getItem('monopoly_language');
    if (saved && LANGUAGES[saved]) currentLang = saved;
}